# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 50.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 788)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OriginalData_Time = PlotWidget(self.centralWidget)
        self.OriginalData_Time.setObjectName("OriginalData_Time")
        self.horizontalLayout_4.addWidget(self.OriginalData_Time)
        self.OriginalData_Freq = PlotWidget(self.centralWidget)
        self.OriginalData_Freq.setObjectName("OriginalData_Freq")
        self.horizontalLayout_4.addWidget(self.OriginalData_Freq)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DataAfterEdit_Time = PlotWidget(self.centralWidget)
        self.DataAfterEdit_Time.setObjectName("DataAfterEdit_Time")
        self.horizontalLayout_5.addWidget(self.DataAfterEdit_Time)
        self.DataAfterEdit_Freq = PlotWidget(self.centralWidget)
        self.DataAfterEdit_Freq.setObjectName("DataAfterEdit_Freq")
        self.horizontalLayout_5.addWidget(self.DataAfterEdit_Freq)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.save = QtWidgets.QPushButton(self.centralWidget)
        self.save.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.save.setObjectName("save")
        self.horizontalLayout_6.addWidget(self.save)
        self.results = QtWidgets.QComboBox(self.centralWidget)
        self.results.setStyleSheet("gridline-color: rgb(55, 110, 165);\n"
"")
        self.results.setObjectName("results")
        self.results.addItem("")
        self.results.addItem("")
        self.horizontalLayout_6.addWidget(self.results)
        self.options = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.options.setFont(font)
        self.options.setStyleSheet("border-left-color: rgb(37, 72, 168);\n"
"font: 8pt \"Microsoft YaHei\";\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.options.setObjectName("options")
        self.options.addItem("")
        self.options.addItem("")
        self.options.setItemText(1, "Hamm")
        self.options.addItem("")
        self.options.addItem("")
        self.horizontalLayout_6.addWidget(self.options)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.slider1 = QtWidgets.QSlider(self.centralWidget)
        self.slider1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider1.setMinimum(-50)
        self.slider1.setMaximum(50)
        self.slider1.setSliderPosition(1)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider1.setObjectName("slider1")
        self.verticalLayout.addWidget(self.slider1)
        self.Gain_Band1 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band1.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band1.setObjectName("Gain_Band1")
        self.verticalLayout.addWidget(self.Gain_Band1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slider2 = QtWidgets.QSlider(self.centralWidget)
        self.slider2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider2.setAutoFillBackground(False)
        self.slider2.setMinimum(-50)
        self.slider2.setMaximum(50)
        self.slider2.setProperty("value", 1)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider2.setObjectName("slider2")
        self.verticalLayout_2.addWidget(self.slider2)
        self.Gain_Band2 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band2.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band2.setMidLineWidth(0)
        self.Gain_Band2.setObjectName("Gain_Band2")
        self.verticalLayout_2.addWidget(self.Gain_Band2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.slider3 = QtWidgets.QSlider(self.centralWidget)
        self.slider3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider3.setMinimum(-50)
        self.slider3.setMaximum(50)
        self.slider3.setProperty("value", 1)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider3.setObjectName("slider3")
        self.verticalLayout_3.addWidget(self.slider3)
        self.Gain_Band3 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band3.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band3.setObjectName("Gain_Band3")
        self.verticalLayout_3.addWidget(self.Gain_Band3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.slider4 = QtWidgets.QSlider(self.centralWidget)
        self.slider4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider4.setMinimum(-50)
        self.slider4.setMaximum(50)
        self.slider4.setProperty("value", 1)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider4.setObjectName("slider4")
        self.verticalLayout_4.addWidget(self.slider4)
        self.Gain_Band4 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band4.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band4.setObjectName("Gain_Band4")
        self.verticalLayout_4.addWidget(self.Gain_Band4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.slider5 = QtWidgets.QSlider(self.centralWidget)
        self.slider5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider5.setMinimum(-50)
        self.slider5.setMaximum(50)
        self.slider5.setProperty("value", 1)
        self.slider5.setOrientation(QtCore.Qt.Vertical)
        self.slider5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider5.setObjectName("slider5")
        self.verticalLayout_5.addWidget(self.slider5)
        self.Gain_Band5 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band5.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band5.setObjectName("Gain_Band5")
        self.verticalLayout_5.addWidget(self.Gain_Band5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.slider6 = QtWidgets.QSlider(self.centralWidget)
        self.slider6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider6.setMinimum(-50)
        self.slider6.setMaximum(50)
        self.slider6.setProperty("value", 1)
        self.slider6.setSliderPosition(1)
        self.slider6.setOrientation(QtCore.Qt.Vertical)
        self.slider6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider6.setObjectName("slider6")
        self.verticalLayout_6.addWidget(self.slider6)
        self.Gain_Band6 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band6.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band6.setObjectName("Gain_Band6")
        self.verticalLayout_6.addWidget(self.Gain_Band6)
        self.verticalLayout_6.setStretch(0, 8)
        self.verticalLayout_6.setStretch(1, 9)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.slider7 = QtWidgets.QSlider(self.centralWidget)
        self.slider7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider7.setMinimum(-50)
        self.slider7.setMaximum(50)
        self.slider7.setProperty("value", 1)
        self.slider7.setOrientation(QtCore.Qt.Vertical)
        self.slider7.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider7.setObjectName("slider7")
        self.verticalLayout_7.addWidget(self.slider7)
        self.Gain_Band7 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band7.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band7.setObjectName("Gain_Band7")
        self.verticalLayout_7.addWidget(self.Gain_Band7)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.slider8 = QtWidgets.QSlider(self.centralWidget)
        self.slider8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider8.setMinimum(-50)
        self.slider8.setMaximum(50)
        self.slider8.setProperty("value", 1)
        self.slider8.setOrientation(QtCore.Qt.Vertical)
        self.slider8.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider8.setObjectName("slider8")
        self.verticalLayout_8.addWidget(self.slider8)
        self.Gain_Band8 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band8.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band8.setObjectName("Gain_Band8")
        self.verticalLayout_8.addWidget(self.Gain_Band8)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.slider9 = QtWidgets.QSlider(self.centralWidget)
        self.slider9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider9.setMinimum(-50)
        self.slider9.setMaximum(50)
        self.slider9.setProperty("value", 1)
        self.slider9.setOrientation(QtCore.Qt.Vertical)
        self.slider9.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider9.setObjectName("slider9")
        self.verticalLayout_9.addWidget(self.slider9)
        self.Gain_Band9 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band9.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band9.setObjectName("Gain_Band9")
        self.verticalLayout_9.addWidget(self.Gain_Band9)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.slider10 = QtWidgets.QSlider(self.centralWidget)
        self.slider10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.slider10.setMouseTracking(True)
        self.slider10.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.slider10.setAcceptDrops(False)
        self.slider10.setAutoFillBackground(False)
        self.slider10.setMinimum(-50)
        self.slider10.setMaximum(50)
        self.slider10.setSingleStep(1)
        self.slider10.setPageStep(10)
        self.slider10.setProperty("value", 1)
        self.slider10.setSliderPosition(1)
        self.slider10.setOrientation(QtCore.Qt.Vertical)
        self.slider10.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider10.setTickInterval(0)
        self.slider10.setObjectName("slider10")
        self.verticalLayout_10.addWidget(self.slider10)
        self.Gain_Band10 = QtWidgets.QLabel(self.centralWidget)
        self.Gain_Band10.setMaximumSize(QtCore.QSize(16777215, 17))
        self.Gain_Band10.setObjectName("Gain_Band10")
        self.verticalLayout_10.addWidget(self.Gain_Band10)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.play = QtWidgets.QPushButton(self.centralWidget)
        self.play.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.play.setObjectName("play")
        self.gridLayout.addWidget(self.play, 0, 1, 1, 1)
        self.browser = QtWidgets.QPushButton(self.centralWidget)
        self.browser.setStyleSheet("\n"
"gridline-color: rgb(255, 255, 255);")
        self.browser.setObjectName("browser")
        self.gridLayout.addWidget(self.browser, 0, 0, 1, 1)
        self.pause = QtWidgets.QPushButton(self.centralWidget)
        self.pause.setStyleSheet("gridline-color: rgb(255, 255, 255);\n"
"")
        self.pause.setObjectName("pause")
        self.gridLayout.addWidget(self.pause, 0, 2, 1, 1)
        self.stop = QtWidgets.QPushButton(self.centralWidget)
        self.stop.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 0, 3, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_16.addWidget(self.progressBar)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.Gain_Band10.raise_()
        self.slider10.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 832, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.results.setItemText(0, _translate("MainWindow", "Diff"))
        self.results.setItemText(1, _translate("MainWindow", "compare"))
        self.options.setItemText(0, _translate("MainWindow", "Default"))
        self.options.setItemText(2, _translate("MainWindow", "Hann"))
        self.options.setItemText(3, _translate("MainWindow", "Rect"))
        self.Gain_Band1.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band2.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band3.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band4.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band5.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band6.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band7.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band8.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band9.setText(_translate("MainWindow", "TextLabel"))
        self.Gain_Band10.setText(_translate("MainWindow", "TextLabel"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.browser.setText(_translate("MainWindow", "Browse"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
from pyqtgraph import PlotWidget
